<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace GPBMetadata;

class Base
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
d

base.protokop"@
Item
ConfId (
Count (
Total (

Id (BZ./kopbproto3'
        , true);

        static::$is_initialized = true;
    }
}

