<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¡

user.protokop" 
User

id (
name (	"
Login
token (	"C
LoginResponse
code (
msg (	
self (2	.kop.UserBZ./kopbproto3'
        , true);

        static::$is_initialized = true;
    }
}

