<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace Kop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kop.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ConfId = 1;</code>
     */
    protected $ConfId = 0;
    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     */
    protected $Count = 0;
    /**
     * Generated from protobuf field <code>int32 Total = 3;</code>
     */
    protected $Total = 0;
    /**
     * Generated from protobuf field <code>int64 Id = 4;</code>
     */
    protected $Id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ConfId
     *     @type int $Count
     *     @type int $Total
     *     @type int|string $Id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ConfId = 1;</code>
     * @return int
     */
    public function getConfId()
    {
        return $this->ConfId;
    }

    /**
     * Generated from protobuf field <code>int32 ConfId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setConfId($var)
    {
        GPBUtil::checkInt32($var);
        $this->ConfId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Total = 3;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->Total;
    }

    /**
     * Generated from protobuf field <code>int32 Total = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->Total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Id = 4;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int64 Id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->Id = $var;

        return $this;
    }

}

